name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.2'
        cache: true

    - name: Build
      env:
        CGO_ENABLED: 0
      run: |
        go build -ldflags="-s -w" -o spot-instance-advisor -v .
        mkdir -p dist
        mv spot-instance-advisor dist/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: spot-instance-advisor
        path: dist/spot-instance-advisor

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/spot-instance-advisor
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
